name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build-n-publish:
    name: Build and publish plugin 📦 to JetBrains merket
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:

     - uses: actions/checkout@v2
     - name: Cache
       uses: actions/cache@v1.1.2
       with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
     - name: Set up JDK 11
       uses: actions/setup-java@v1
       with:
        java-version: 11
     - name: test 
       run: ./gradlew buildPlugin test jacocoTestReport
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: ${{ github.ref }}
         release_name: Release ${{ github.ref }}
         body: |
            ${{ env.CHANGELOG_LATEST }}
         draft: false
         prerelease: false
     - name: Upload Release Asset
       id: upload-release-asset 
       uses: actions/upload-release-asset@v1
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/htmpy-pycharm-plugin.zip
          asset_name: htmpy-pycharm-plugin.zip
          asset_content_type: application/zip
#     - name: Publish a plugin
#       run: |
#         curl --fail --header "Authorization: Bearer ${{secrets.JETBRAINS_TOKEN}}" \
#               -F pluginId=xxx -F file=@build/distributions/htmpy-pycharm-plugin.zip \
#                https://plugins.jetbrains.com/plugin/uploadPlugin
